[workspace] 
members = [
    "genetic_algorithm", 
    "genetic_framework", 
    "population", 
    "loader_config", 
    "loader_config", 
    "problem_factory", 
    "ga_cli", 
    "benchmarks",
]
resolver = "2"

[profile.release]
debug = 1
opt-level = 3
