[workspace] 
members = [
    "genetic_algorithm", 
    "genetic_framework", 
    "individual_creation", 
    "loader_config", 
    "problem", 
    "sat_3",
    "loader_config"
, "problem_factory", "ga_cli"]
resolver = "2"
