[package]
name = "problem_factory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loader_config = {path = "../loader_config"}
population = {path="../population"}
rayon = {version = "1.10.0"}